In [13]:
import pandas as pd

# read csv using pd
# Data will have to be download from https://databank.worldbank.org/source/world-development-indicators# and redirected. 
df = pd.read_csv('wdi_raw.csv')

# filter df
list_of_series_code = ['NY.GDP.PCAP.KD', 'EN.POP.DNST']
new_df = df[df['Indicator Code'].isin(list_of_series_code)]

# write to csv
new_df.to_csv('wdi.csv', index=False)

In [12]:
new_df

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
469,Africa Eastern and Southern,AFE,GDP per capita (constant 2015 US$),NY.GDP.PCAP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1516.765962,1505.094307,1527.750571,1546.133379,1549.037940,1538.589175,1536.362686,1533.514183,1525.165516,1442.748310
1912,Africa Western and Central,AFW,GDP per capita (constant 2015 US$),NY.GDP.PCAP.KD,1087.63480,1085.107082,1102.493743,1157.515620,1193.684274,1214.978972,...,1738.993397,1779.254136,1837.273584,1894.169982,1894.310195,1846.316666,1839.103754,1843.545758,1852.633574,1788.644061
3355,Arab World,ARB,GDP per capita (constant 2015 US$),NY.GDP.PCAP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,5937.504498,6097.822797,6142.058917,6165.953239,6220.716636,6292.438934,6229.114480,6258.315712,6266.949961,5824.178548
4798,Caribbean small states,CSS,GDP per capita (constant 2015 US$),NY.GDP.PCAP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,10049.923350,10111.906490,10102.609130,10102.335770,10141.415390,9960.517993,9907.312552,10032.486840,10036.417120,9166.657179
6241,Central Europe and the Baltics,CEB,GDP per capita (constant 2015 US$),NY.GDP.PCAP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,11365.752810,11478.772540,11645.854570,12018.516360,12521.791410,12939.285960,13604.116100,14243.054240,14843.307770,14297.505710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
377092,Virgin Islands (U.S.),VIR,GDP per capita (constant 2015 US$),NY.GDP.PCAP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,43320.176770,36938.168210,34663.646060,34098.711000,34007.352940,34614.748260,34435.494450,35073.630660,35961.580770,NaN
378535,West Bank and Gaza,PSE,GDP per capita (constant 2015 US$),NY.GDP.PCAP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,3128.108111,3237.916200,3309.631202,3227.849345,3272.154324,3483.099035,3462.979861,3417.794408,3378.434621,2917.887797
379978,"Yemen, Rep.",YEM,GDP per capita (constant 2015 US$),NY.GDP.PCAP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2311.205082,2302.148290,2348.517585,2282.691868,1601.830063,1415.839376,1311.843419,1290.925239,NaN,NaN
381421,Zambia,ZMB,GDP per capita (constant 2015 US$),NY.GDP.PCAP.KD,1219.78730,1199.840632,1135.395669,1137.844509,1238.805910,1401.627437,...,1244.137787,1297.762597,1321.248838,1340.810981,1338.290927,1347.748086,1354.407115,1368.601756,1348.738357,1273.879558
382864,Zimbabwe,ZWE,GDP per capita (constant 2015 US$),NY.GDP.PCAP.KD,1164.74025,1197.603795,1174.431444,1206.107233,1152.997692,1169.489415,...,1248.729206,1432.305854,1435.062663,1443.617777,1445.069702,1433.608776,1479.376056,1529.026374,1414.829099,1307.013630